/* Afterschool Pascal runtime library -- the text primitives.
 * Copyright (C) 2026 Hui-Hong You
 *
 * This library is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 * for more details.
 *
 * As a special exception, if you link this library with other files to
 * produce an executable, that does not by itself cause the resulting
 * executable to be covered by the GNU General Public License.  This exception
 * does not however invalidate any other reasons why the executable file might
 * be covered by the GNU General Public License.  See COPYING.RUNTIME.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

/* AP 6.4.15: Normalization Form C, and where one element ends.
 *
 * This file is strict ISO C11 and calls nothing outside it -- no allocation,
 * no locale, no POSIX. That is not incidental: it is the only part of the
 * runtime whose correctness is settled by a document written elsewhere, and
 * keeping it self-contained is what lets `unicode-conformance` compile it on
 * its own and run Unicode's own answers through it (ADR-0189).
 *
 * The data is in pasrt_unicode_data.h, generated by runtime/unicode/
 * generate.py from the pinned database. Nothing in this file states a fact
 * about a character; every such fact is looked up there. */

#include "pasrt_unicode.h"

#include <stddef.h>

#include "pasrt_unicode_data.h"

/* Hangul decomposes and composes arithmetically (The Unicode Standard 3.12),
 * which is why 11 172 syllables are in no table. generate.py asserts that none
 * of them acquired one. */
#define S_BASE 0xAC00u
#define L_BASE 0x1100u
#define V_BASE 0x1161u
#define T_BASE 0x11A7u
#define L_COUNT 19u
#define V_COUNT 21u
#define T_COUNT 28u
#define N_COUNT (V_COUNT * T_COUNT)
#define S_COUNT (L_COUNT * N_COUNT)

/* Grapheme_Cluster_Break, numbered as generate.py numbers it. The two lists
 * are one list and must be read together; the generator's GCB array is the
 * other half. */
enum {
  GCB_OTHER = 0,
  GCB_CR,
  GCB_LF,
  GCB_CONTROL,
  GCB_EXTEND,
  GCB_ZWJ,
  GCB_RI,
  GCB_PREPEND,
  GCB_SPACINGMARK,
  GCB_L,
  GCB_V,
  GCB_T,
  GCB_LV,
  GCB_LVT
};

/* Indic_Conjunct_Break, likewise. InCB=Extend is a different property from
 * GCB=Extend and the two are not interchangeable in GB9c. */
enum { INCB_NONE = 0, INCB_CONSONANT, INCB_EXTEND, INCB_LINKER };

/* --- the tables, by bisection ------------------------------------------- */

static unsigned int range_lookup(const struct pas_u_range *tbl, size_t n,
                                 unsigned int cp) {
  size_t lo = 0, hi = n;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (cp < tbl[mid].lo)
      hi = mid;
    else if (cp > tbl[mid].hi)
      lo = mid + 1;
    else
      return tbl[mid].v;
  }
  return 0;
}

static unsigned int u_ccc(unsigned int cp) {
  return range_lookup(pas_u_ccc, PAS_U_CCC_N, cp);
}

static unsigned int u_gcb(unsigned int cp) {
  return range_lookup(pas_u_gcb, PAS_U_GCB_N, cp);
}

static unsigned int u_incb(unsigned int cp) {
  return range_lookup(pas_u_incb, PAS_U_INCB_N, cp);
}

static int u_extpict(unsigned int cp) {
  return range_lookup(pas_u_extpict, PAS_U_EXTPICT_N, cp) != 0;
}

/* Can this code point be the *second* element of a composition? A starter that
 * can is not a place a normalisation segment may be taken to begin -- 59
 * primary composites have a starter on the right, across sixteen Indic and
 * Southeast Asian scripts, and Hangul V and T are the same case computed rather
 * than tabulated. Getting this wrong loses exactly those compositions and
 * nothing else, which is a defect a spot check does not find. */
static int combines_back(unsigned int cp) {
  if (cp >= V_BASE && cp < V_BASE + V_COUNT)
    return 1;
  if (cp > T_BASE && cp < T_BASE + T_COUNT)
    return 1;
  return range_lookup(pas_u_combines_back, PAS_U_COMBINES_BACK_N, cp) != 0;
}

static const struct pas_u_decomp *decomp_lookup(unsigned int cp) {
  size_t lo = 0, hi = PAS_U_DECOMP_N;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (cp < pas_u_decomp_tbl[mid].cp)
      hi = mid;
    else if (cp > pas_u_decomp_tbl[mid].cp)
      lo = mid + 1;
    else
      return &pas_u_decomp_tbl[mid];
  }
  return NULL;
}

static unsigned int compose_pair(unsigned int a, unsigned int b) {
  size_t lo = 0, hi = PAS_U_COMPOSE_N;

  /* Hangul first, and by arithmetic: L + V makes an LV syllable, and an LV
   * syllable + T makes an LVT one. */
  if (a >= L_BASE && a < L_BASE + L_COUNT && b >= V_BASE &&
      b < V_BASE + V_COUNT)
    return S_BASE + ((a - L_BASE) * V_COUNT + (b - V_BASE)) * T_COUNT;
  if (a >= S_BASE && a < S_BASE + S_COUNT && (a - S_BASE) % T_COUNT == 0 &&
      b > T_BASE && b < T_BASE + T_COUNT)
    return a + (b - T_BASE);

  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    const struct pas_u_compose *e = &pas_u_compose_tbl[mid];
    if (a < e->a || (a == e->a && b < e->b))
      hi = mid;
    else if (a > e->a || (a == e->a && b > e->b))
      lo = mid + 1;
    else
      return e->cp;
  }
  return 0;
}

/* --- UTF-8 --------------------------------------------------------------- */

/* One scalar from s[i..n). Answers the bytes consumed, or 0 when the sequence
 * is not well-formed.
 *
 * The ranges are The Unicode Standard's Table 3-7 and not a byte-count rule:
 * an overlong encoding, a surrogate and anything above U+10FFFF each have a
 * lead byte that looks ordinary, so the *second* byte's admissible range
 * depends on the first. Writing this as "read k continuation bytes" is the
 * classic way to admit all three. */
static int u8dec(const unsigned char *s, long long n, long long i,
                 unsigned int *out) {
  unsigned int c = s[i];
  unsigned int lo2, hi2;
  int k;

  if (c < 0x80u) {
    *out = c;
    return 1;
  }
  if (c >= 0xC2u && c <= 0xDFu) {
    k = 2;
    lo2 = 0x80u;
    hi2 = 0xBFu;
  } else if (c == 0xE0u) {
    k = 3;
    lo2 = 0xA0u;
    hi2 = 0xBFu;
  } else if (c == 0xEDu) {
    k = 3;
    lo2 = 0x80u;
    hi2 = 0x9Fu;
  } else if (c >= 0xE1u && c <= 0xEFu) {
    k = 3;
    lo2 = 0x80u;
    hi2 = 0xBFu;
  } else if (c == 0xF0u) {
    k = 4;
    lo2 = 0x90u;
    hi2 = 0xBFu;
  } else if (c == 0xF4u) {
    k = 4;
    lo2 = 0x80u;
    hi2 = 0x8Fu;
  } else if (c >= 0xF1u && c <= 0xF3u) {
    k = 4;
    lo2 = 0x80u;
    hi2 = 0xBFu;
  } else {
    return 0;
  }

  if (i + k > n)
    return 0;
  if (s[i + 1] < lo2 || s[i + 1] > hi2)
    return 0;
  for (int j = 2; j < k; j++)
    if (s[i + j] < 0x80u || s[i + j] > 0xBFu)
      return 0;

  c &= (unsigned int)(0x7Fu >> k);
  for (int j = 1; j < k; j++)
    c = (c << 6) | (s[i + j] & 0x3Fu);
  *out = c;
  return k;
}

/* The bytes cp occupies. */
static int u8len(unsigned int cp) {
  if (cp < 0x80u)
    return 1;
  if (cp < 0x800u)
    return 2;
  if (cp < 0x10000u)
    return 3;
  return 4;
}

/* cp into dst, which shall have u8len(cp) bytes. cp is a scalar value: it came
 * out of u8dec or out of a table, so there is nothing here to reject. */
static int u8enc(unsigned int cp, char *dst) {
  int k = u8len(cp);
  switch (k) {
  case 1:
    dst[0] = (char)cp;
    break;
  case 2:
    dst[0] = (char)(0xC0u | (cp >> 6));
    dst[1] = (char)(0x80u | (cp & 0x3Fu));
    break;
  case 3:
    dst[0] = (char)(0xE0u | (cp >> 12));
    dst[1] = (char)(0x80u | ((cp >> 6) & 0x3Fu));
    dst[2] = (char)(0x80u | (cp & 0x3Fu));
    break;
  default:
    dst[0] = (char)(0xF0u | (cp >> 18));
    dst[1] = (char)(0x80u | ((cp >> 12) & 0x3Fu));
    dst[2] = (char)(0x80u | ((cp >> 6) & 0x3Fu));
    dst[3] = (char)(0x80u | (cp & 0x3Fu));
    break;
  }
  return k;
}

const char *pas_text_unicode_version(void) { return PAS_UNICODE_VERSION; }

long long pas_text_validate(const char *s, long long n) {
  const unsigned char *u = (const unsigned char *)s;
  long long i = 0;
  while (i < n) {
    unsigned int cp;
    int k = u8dec(u, n, i, &cp);
    if (k == 0)
      return i;
    i += k;
  }
  return -1;
}

/* --- Normalization Form C ------------------------------------------------ */

/* One starter and the marks that belong to it. Unicode places no bound on how
 * many marks may follow a base character, so this is a limit of the
 * implementation and PAS_TEXT_SEGMENT is where it is reported rather than
 * exceeded (ADR-0110). Real text does not approach it: the longest segment in
 * NormalizationTest.txt is six -- a base letter and five marks. */
#define SEGMENT_MAX 256

/* cp fully decomposed, recursively, into out. Answers how many code points.
 * PAS_U_DECOMP_MAX is measured from the database by the generator, so a
 * release that made a decomposition wider moves the array rather than
 * overrunning it. */
static int decompose(unsigned int cp, unsigned int *out) {
  const struct pas_u_decomp *e;
  int n;

  if (cp >= S_BASE && cp < S_BASE + S_COUNT) {
    unsigned int si = cp - S_BASE;
    unsigned int ti = si % T_COUNT;
    out[0] = L_BASE + si / N_COUNT;
    out[1] = V_BASE + (si % N_COUNT) / T_COUNT;
    if (ti == 0)
      return 2;
    out[2] = T_BASE + ti;
    return 3;
  }

  e = decomp_lookup(cp);
  if (e == NULL) {
    out[0] = cp;
    return 1;
  }
  n = decompose(e->a, out);
  if (e->b != 0)
    n += decompose(e->b, out + n);
  return n;
}

/* Canonical ordering: a stable sort of each run of non-starters by combining
 * class. Insertion sort, because a run is short and stability is the whole
 * requirement -- two marks of equal class must keep the order they were
 * written in, that being the difference between reordering and rewriting. */
static void canonical_order(unsigned int *buf, int len) {
  for (int i = 1; i < len; i++) {
    unsigned int c = u_ccc(buf[i]);
    int j = i;
    if (c == 0)
      continue;
    while (j > 0 && u_ccc(buf[j - 1]) > c) {
      unsigned int t = buf[j - 1];
      buf[j - 1] = buf[j];
      buf[j] = t;
      j--;
    }
  }
}

/* UAX #15's canonical composition, applied to one already-ordered segment.
 * Answers the new length.
 *
 * The `last` variable is the one part that is not obvious: a starter whose own
 * combining class is not zero cannot exist, but a *segment* may begin with a
 * non-starter when the text does, and then nothing may compose onto it. 256 is
 * above every real class and is how that is said. */
static int compose_segment(unsigned int *buf, int len) {
  int start = 0, put = 1;
  unsigned int head, last;

  if (len < 2)
    return len;

  head = buf[0];
  last = u_ccc(head);
  if (last != 0)
    last = 256;

  for (int i = 1; i < len; i++) {
    unsigned int cp = buf[i];
    unsigned int cls = u_ccc(cp);
    unsigned int made = compose_pair(head, cp);

    if (made != 0 && (last < cls || last == 0)) {
      buf[start] = made;
      head = made;
      continue;
    }
    if (cls == 0) {
      start = put;
      head = cp;
    }
    last = cls;
    buf[put++] = cp;
  }
  return put;
}

/* Order, compose and encode one segment. Answers the new output length or a
 * negative status. */
static long long flush_segment(unsigned int *buf, int len, char *dst,
                               long long cap, long long out) {
  canonical_order(buf, len);
  len = compose_segment(buf, len);
  for (int i = 0; i < len; i++) {
    int k = u8len(buf[i]);
    if (out + k > cap)
      return PAS_TEXT_OVERFLOW;
    out += u8enc(buf[i], dst + out);
  }
  return out;
}

long long pas_text_nfc(const char *s, long long n, char *dst, long long cap) {
  const unsigned char *u = (const unsigned char *)s;
  unsigned int buf[SEGMENT_MAX];
  int len = 0;
  long long i = 0, out = 0;

  while (i < n) {
    unsigned int cp;
    unsigned int d[PAS_U_DECOMP_MAX];
    int dn;
    int k = u8dec(u, n, i, &cp);
    if (k == 0)
      return PAS_TEXT_ILLFORMED;
    i += k;
    dn = decompose(cp, d);

    /* A new segment begins here only if nothing already held can reach across
     * -- a starter that does not combine backwards. */
    if (len > 0 && u_ccc(d[0]) == 0 && !combines_back(d[0])) {
      out = flush_segment(buf, len, dst, cap, out);
      if (out < 0)
        return out;
      len = 0;
    }
    if (len + dn > SEGMENT_MAX)
      return PAS_TEXT_SEGMENT;
    for (int j = 0; j < dn; j++)
      buf[len++] = d[j];
  }

  if (len > 0) {
    out = flush_segment(buf, len, dst, cap, out);
    if (out < 0)
      return out;
  }
  return out;
}

/* --- case folding and case mapping ---------------------------------------
 *
 * The one part of this file with **no conformance file behind it**. Unicode
 * publishes an answer for normalisation and for segmentation and none for
 * casing, so what stands behind these is that the tables are a transcription
 * and this is a table walk over them (ADR-0196).
 *
 * All three are *full* mappings: one code point may become three, which is
 * why they cannot be done in place and why the length is answered rather than
 * assumed. Every locale- or context-conditional mapping is declined -- final
 * sigma, Turkic dotted i -- so what these implement is the unconditional
 * default and nothing about any language. */

static const struct pas_u_case *case_lookup(const struct pas_u_case *tbl,
                                            size_t n, unsigned int cp) {
  size_t lo = 0, hi = n;
  while (lo < hi) {
    size_t mid = lo + (hi - lo) / 2;
    if (cp < tbl[mid].cp)
      hi = mid;
    else if (cp > tbl[mid].cp)
      lo = mid + 1;
    else
      return &tbl[mid];
  }
  return NULL;
}

/* One scalar through one of the three tables, into out[0..2]. Answers how
 * many; a code point with no entry maps to itself. */
static int case_map(const struct pas_u_case *tbl, size_t n, unsigned int cp,
                    unsigned int *out) {
  const struct pas_u_case *e = case_lookup(tbl, n, cp);
  if (e == NULL) {
    out[0] = cp;
    return 1;
  }
  out[0] = e->a;
  out[1] = e->b;
  out[2] = e->c;
  return e->n;
}

static long long case_all(const struct pas_u_case *tbl, size_t n,
                          const char *s, long long len, char *dst,
                          long long cap) {
  const unsigned char *u = (const unsigned char *)s;
  long long i = 0, out = 0;

  if (len < 0)
    len = 0;
  while (i < len) {
    unsigned int cp, to[3];
    int k = u8dec(u, len, i, &cp);
    int m, j;
    if (k == 0)
      return PAS_TEXT_ILLFORMED;
    i += k;
    m = case_map(tbl, n, cp, to);
    for (j = 0; j < m; j++) {
      int w = u8len(to[j]);
      if (out + w > cap)
        return PAS_TEXT_OVERFLOW;
      out += u8enc(to[j], dst + out);
    }
  }
  return out;
}

long long pas_text_fold(const char *s, long long n, char *dst, long long cap) {
  return case_all(pas_u_fold, PAS_U_FOLD_N, s, n, dst, cap);
}

long long pas_text_upper(const char *s, long long n, char *dst, long long cap) {
  return case_all(pas_u_upper, PAS_U_UPPER_N, s, n, dst, cap);
}

long long pas_text_lower(const char *s, long long n, char *dst, long long cap) {
  return case_all(pas_u_lower, PAS_U_LOWER_N, s, n, dst, cap);
}

/* --- UAX #29, extended grapheme clusters --------------------------------- */

/* What the scan remembers about what it has already passed. Each field serves
 * exactly one rule, and each is a rule that looks further back than one code
 * point -- which is the reason a boundary cannot be decided from a pair. */
struct scan {
  int ri;    /* consecutive Regional_Indicators, for GB12 and GB13 */
  int pict;  /* 0 none, 1 ExtPict Extend*, 2 ExtPict Extend* ZWJ -- GB11 */
  int incb;  /* 0 none, 1 Consonant [Ext|Link]*, 2 with a Linker -- GB9c */
  unsigned int gcb; /* the previous code point's break property */
};

static void scan_step(struct scan *st, unsigned int cp) {
  unsigned int g = u_gcb(cp);
  unsigned int ic = u_incb(cp);

  st->ri = (g == GCB_RI) ? st->ri + 1 : 0;

  if (u_extpict(cp))
    st->pict = 1;
  else if (g == GCB_EXTEND && st->pict == 1)
    st->pict = 1;
  else if (g == GCB_ZWJ && st->pict == 1)
    st->pict = 2;
  else
    st->pict = 0;

  if (ic == INCB_CONSONANT)
    st->incb = 1;
  else if (st->incb != 0 && ic == INCB_LINKER)
    st->incb = 2;
  else if (st->incb != 0 && ic == INCB_EXTEND)
    ; /* a mark that is neither: the run continues, linked or not */
  else
    st->incb = 0;

  st->gcb = g;
}

/* Is there a boundary between what `st` has passed and `cp`? The rules are
 * UAX #29's GB3 to GB999 and they are tried in the standard's own order,
 * because they overlap: GB4 breaks after a Control that GB9 would otherwise
 * join to a following Extend. */
static int breaks_before(const struct scan *st, unsigned int cp) {
  unsigned int g = u_gcb(cp);

  if (st->gcb == GCB_CR && g == GCB_LF) /* GB3 */
    return 0;
  if (st->gcb == GCB_CONTROL || st->gcb == GCB_CR || st->gcb == GCB_LF) /* GB4 */
    return 1;
  if (g == GCB_CONTROL || g == GCB_CR || g == GCB_LF) /* GB5 */
    return 1;
  if (st->gcb == GCB_L &&
      (g == GCB_L || g == GCB_V || g == GCB_LV || g == GCB_LVT)) /* GB6 */
    return 0;
  if ((st->gcb == GCB_LV || st->gcb == GCB_V) &&
      (g == GCB_V || g == GCB_T)) /* GB7 */
    return 0;
  if ((st->gcb == GCB_LVT || st->gcb == GCB_T) && g == GCB_T) /* GB8 */
    return 0;
  if (g == GCB_EXTEND || g == GCB_ZWJ) /* GB9 */
    return 0;
  if (g == GCB_SPACINGMARK) /* GB9a */
    return 0;
  if (st->gcb == GCB_PREPEND) /* GB9b */
    return 0;
  if (st->incb == 2 && u_incb(cp) == INCB_CONSONANT) /* GB9c */
    return 0;
  if (st->pict == 2 && u_extpict(cp)) /* GB11 */
    return 0;
  if (st->gcb == GCB_RI && g == GCB_RI && (st->ri % 2) == 1) /* GB12, GB13 */
    return 0;
  return 1; /* GB999 */
}

long long pas_text_next(const char *s, long long n, long long at) {
  const unsigned char *u = (const unsigned char *)s;
  struct scan st = {0, 0, 0, GCB_OTHER};
  unsigned int cp;
  long long i = at;
  int k;

  if (at >= n)
    return n;

  k = u8dec(u, n, i, &cp);
  if (k == 0)
    return i + 1; /* not well-formed: one byte, so a caller still terminates */
  scan_step(&st, cp);
  i += k;

  while (i < n) {
    k = u8dec(u, n, i, &cp);
    if (k == 0)
      return i;
    if (breaks_before(&st, cp))
      return i;
    scan_step(&st, cp);
    i += k;
  }
  return n;
}

long long pas_text_scalar_at(const char *s, long long n, long long at,
                             unsigned int *out) {
  if (at < 0 || at >= n || out == NULL)
    return 0;
  return u8dec((const unsigned char *)s, n, at, out);
}

long long pas_text_count(const char *s, long long n) {
  long long i = 0, count = 0;
  while (i < n) {
    i = pas_text_next(s, n, i);
    count++;
  }
  return count;
}
