#!/usr/bin/env python3
# Afterschool Pascal -- an ISO 7185 / ISO/IEC 10206:1991 Pascal compiler.
# Copyright (C) 2026 Hui-Hong You
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.

"""The dialect's clause numbers and headings, from the specification itself.

The two ISO tables beside this one are extracted from PDFs that are not in this
repository and may not be (clauses/extract.sh). This one has the opposite
problem and the opposite solution: the document *is* here, so the table is
generated from it rather than transcribed, and the two cannot drift.

Run it after editing doc/afterschool-pascal-spec.md:

    python3 tests/spec/clauses/extract_afterschool.py

A clause is a numbered heading (## 5.1 Processors) or a numbered bold lead-in
(**6.4.2.6.1 Values.**), which is the form the specification uses where a
requirement is finer than a heading. Both carry a number and a title, which is
all a citation needs.
"""

import pathlib
import re
import sys

HERE = pathlib.Path(__file__).resolve().parent
SPEC = HERE.parent.parent.parent / "doc" / "afterschool-pascal-spec.md"
OUT = HERE / "afterschool.tsv"

HEADING = re.compile(r"^#{2,6}\s+(\d+(?:\.\d+)*)\s+(.*?)\s*$")
LEADIN = re.compile(r"^\*\*(\d+(?:\.\d+)+)\s+(.*?)\.?\*\*")


def clean(title):
    """The heading text as a citation needs it: no emphasis, no status tag."""
    title = re.sub(r"\s*\[(added|extended|unchanged)\]\s*$", "", title)
    title = re.sub(r"`([^`]*)`", r"\1", title)
    title = re.sub(r"\*\*|\*|~~", "", title)
    return title.strip().rstrip(".")


def main():
    if not SPEC.exists():
        print(f"extract_afterschool: no {SPEC}", file=sys.stderr)
        return 1
    rows, seen = [], set()
    for line in SPEC.read_text(encoding="utf-8").splitlines():
        m = HEADING.match(line) or LEADIN.match(line)
        if not m:
            continue
        number, title = m.group(1), clean(m.group(2))
        if number in seen:
            print(f"extract_afterschool: {number} appears twice", file=sys.stderr)
            return 1
        seen.add(number)
        rows.append((number, title))

    def key(n):
        return [int(p) for p in n.split(".")]

    rows.sort(key=lambda r: key(r[0]))
    with OUT.open("w", encoding="utf-8") as f:
        f.write("# Clause numbers and headings of doc/afterschool-pascal-spec.md.\n")
        f.write("# Generated by tests/spec/clauses/extract_afterschool.py --\n")
        f.write("# regenerate it when the specification gains or renames a clause.\n")
        for number, title in rows:
            f.write(f"{number}\t{title}\n")
    print(f"extract_afterschool: {len(rows)} clauses -> {OUT.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
