#!/usr/bin/env python3
# Afterschool Pascal -- an ISO 7185 / ISO/IEC 10206:1991 Pascal compiler.
# Copyright (C) 2026 Hui-Hong You
#
# This program is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program.  If not, see <https://www.gnu.org/licenses/>.

"""Clause numbers and their headings, and nothing else.

Called by extract.sh, which has the provenance note. What this writes is the
*structure* of a standard -- the numbers a citation names and the few words
each is titled -- never its text. tests/spec/README.md says why that boundary
is where it is.

One wrinkle worth keeping: ISO 7185's online copy renders a clause number with
spaces around the dots ("6 .8 .3 .9 For-statements"), a kerning artefact of the
PDF rather than anything in the document, so the number is normalised before
use. ISO/IEC 10206's copy does not. Extracting one and assuming the other
yields five headings out of a hundred and seventeen, which looks like a thin
standard rather than a broken regex.
"""

import re
import sys

# A heading is a number, then a title beginning with a capital. Anything that
# runs on into a sentence is body text that happens to start with a citation --
# the length bound and the character class are what separate the two.
HEADING = re.compile(r"^\s*(\d+(?:\s*\.\s*\d+)+)\s+([A-Z][A-Za-z0-9 ,'()/-]{2,60})\s*$")

# The two PDFs lose the fi/fl ligatures, in different ways: ISO 7185 emits the
# pair as a token of its own ("Implementation-de fi ned") and ISO/IEC 10206
# drops it ("Schema-de nitions"). Neither is how the standard spells the word,
# so repairing it here is restoring the heading rather than editing it -- and
# leaving it would put "Schema-de nitions" in a committed file, where the next
# reader would take it for the clause's actual title.
#
# Eleven headings are affected. Deliberately a short explicit list rather than a
# general "insert fi where a word looks broken": a rule that guesses would
# silently mangle a title that is merely unusual.
LIGATURES = [
    (r"(?<=\w) fi (?=\w)", "fi"),
    (r"\bde ned\b", "defined"),
    (r"de nition", "definition"),
    (r"Identi er", "Identifier"),
    (r"identi ed", "identified"),
    (r"Identi ed", "Identified"),
    (r"\bxed-point\b", "fixed-point"),
    (r"speci cation", "specification"),
]


def repair(title):
    for pattern, replacement in LIGATURES:
        title = re.sub(pattern, replacement, title)
    return title


def clauses(text):
    found = {}
    for line in text.splitlines():
        m = HEADING.match(line)
        if not m:
            continue
        number = re.sub(r"\s+", "", m.group(1))
        title = repair(re.sub(r"\s+", " ", m.group(2)).strip())
        # The first occurrence wins: a heading repeated in a running header is
        # the same clause, and the table of contents lists it before the body.
        if number.count(".") >= 1 and len(title) > 2:
            found.setdefault(number, title)
    return found


def key(number):
    return [int(part) for part in number.split(".")]


def main():
    if len(sys.argv) != 4:
        print("usage: extract.py <text> <out.tsv> <standard-name>", file=sys.stderr)
        return 2
    src, out, standard = sys.argv[1], sys.argv[2], sys.argv[3]
    with open(src, encoding="utf-8", errors="replace") as f:
        found = clauses(f.read())
    if len(found) < 50:
        print(f"extract: only {len(found)} headings found in {src} -- the "
              "layout changed, and a short inventory would silently understate "
              "clause coverage", file=sys.stderr)
        return 1
    with open(out, "w", encoding="utf-8") as f:
        f.write(f"# Clause numbers and headings of {standard}.\n")
        f.write("# Generated by tests/spec/clauses/extract.sh -- structure "
                "only, no text of the standard.\n")
        for number in sorted(found, key=key):
            f.write(f"{number}\t{found[number]}\n")
    print(f"extract: {len(found)} clauses -> {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
